### ISSUE TITLE
Error: Cannot find module 'underscore' on Node 14.19.1

### ISSUE THREAD

**Issue by seantcanavan** [Learnosity/learnosity-sdk-nodejs#13]
Steps to reproduct:

1. `git clone https://github.com/Learnosity/learnosity-sdk-nodejs`
2. `cd learnosity-sdk-nodejs/docs/quickstart`
3. `npm run start-standalone-assessment`

Full error message:

```
Mon May 23 02:15 PM quickstart: npm run start-standalone-assessment

> lrn-node-sdk-demo@1.0.0 start-standalone-assessment /home/userwork/github/learnosity-sdk-nodejs/docs/quickstart
> npm install && node ./assessment/standalone-assessment.js

npm WARN lrn-node-sdk-demo@1.0.0 No description
npm WARN lrn-node-sdk-demo@1.0.0 No repository field.

audited 75 packages in 0.541s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'underscore'
Require stack:
- /home/userwork/github/learnosity-sdk-nodejs/index.js
- /home/userwork/github/learnosity-sdk-nodejs/docs/quickstart/assessment/standalone-assessment.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/userwork/github/learnosity-sdk-nodejs/index.js:13:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/userwork/github/learnosity-sdk-nodejs/index.js',
    '/home/userwork/github/learnosity-sdk-nodejs/docs/quickstart/assessment/standalone-assessment.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lrn-node-sdk-demo@1.0.0 start-standalone-assessment: `npm install && node ./assessment/standalone-assessment.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lrn-node-sdk-demo@1.0.0 start-standalone-assessment script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/userwork/.npm/_logs/2022-05-23T19_15_31_686Z-debug.log
```

Steps I've tried to fix it:

1. `npm update`
2. `npm install underscore`
3. `npm install express`
4. `npm install ejs`
5. `npm install uuid`

This is with Node 14.19.1:

```
Mon May 23 02:17 PM quickstart: nvm install 14.19.1
v14.19.1 is already installed.
Now using node v14.19.1 (npm v6.14.16)
Mon May 23 02:17 PM quickstart: nvm use
Found '/home/userwork/github/learnosity-sdk-nodejs/docs/quickstart/.nvmrc' with version <14.19.1>
Now using node v14.19.1 (npm v6.14.16)
```

I'm nowhere near a Node expert however the docs say it's been tested on all major LTS releases and 14 is in maintenance mode so should be mature enough for most projects to use by now. https://github.com/Learnosity/learnosity-sdk-nodejs#supported-nodejs-versions

**Comment by seantcanavan** [comment]
It looks like there are multiple `package.json` files within the application. If you use the inner one to run `npm install` - it won't install `undercore`. And it also won't work if you install it manually via `npm install understore`. The trick is to navigate to the outer `package.json` file and run `npm install` there. 

The docs are slightly unclear on this however as the section for downloading the repo doesn't mention anything after `git clone` - forcing the user to guess where to run the app from.

**Comment by TheRealEdDawson** [comment]
@seantcanavan Thanks for this report. We've updated the README instructions to specify the ideal location to run those installation commands. https://github.com/Learnosity/learnosity-sdk-nodejs/blob/master/README.md
